### PR TITLE
Better fix for #390 - Use AddGadget, but only when needed

### PR DESCRIPTION
**Pull request by vlyon**
This fixes the duplicate gadget exception by only using AddGadget when needed. (More efficient)

### CODE REVIEW

**Comment by 32Kallies** [comment]
Personally I preferred it the old way since it had less duplication of the "functional" code and property setting, but it's really personal preference. We can ask other contributors what they prefer.

**Comment by vlyon** [comment]
This way actually has less duplication and less redundant code. It makes use of the return value of `TryGetGadget` instead of ignoring it and then trying to add the gadget again. This way it also avoids setting properties when the newly created gadgets have just been initialised with those properties.

**Comment by 32Kallies** [comment]
I already asked ECM and I think she didn't mind either way. I'll ask one other "maintainer" and see what they think.

**Comment by JKohlman** [comment]
Ask and you shall receive an even harder decision, A THIRD OPTION!

```cs
public static CraftingGadget SetRecipe(this ICustomPrefab customPrefab, RecipeData recipeData)
{
    if (!customPrefab.TryGetGadget(out CraftingGadget craftingGadget))
        return customPrefab.AddGadget(new CraftingGadget(customPrefab, recipeData));
    craftingGadget.RecipeData = recipeData;
    return craftingGadget;
}
```

**Comment by 32Kallies** [comment]
> Ask and you shall receive an even harder decision, A THIRD OPTION!
> 
> ```cs
> public static CraftingGadget SetRecipe(this ICustomPrefab customPrefab, RecipeData recipeData)
> {
>     if (!customPrefab.TryGetGadget(out CraftingGadget craftingGadget))
>         return customPrefab.AddGadget(new CraftingGadget(customPrefab, recipeData));
>     craftingGadget.RecipeData = recipeData;
>     return craftingGadget;
> }
> ```

I prefer this

**Review by 32Kallies — CHANGES_REQUESTED** [review]
I suggest that the code should be reformatted to fit [this suggestion](https://github.com/SubnauticaModding/Nautilus/pull/404#issuecomment-1595807122).

**Review by 32Kallies — APPROVED** [review]

**Review by JKohlman — APPROVED** [review]

**Pull request merged**
