### PR TITLE
Allow controllers to use options menu

### LINKED ISSUE #263: KeyCode from ConfigFile input doesn't recognize controller
I'll probably fix this, just tracking the issue.

When I try to use KeyCode in [QuickSlots+](https://www.nexusmods.com/subnautica/mods/984) it allows my 360 controller to activate the input, but it doesn't recognize any inputs afterwords except from keyboard.

For reference: https://github.com/celvro/QuickSlotsPlus/blob/53a81b7cac80ee491e0f398cedcdb336ecf5847b/StandardConfig.cs#L25-L65

In a related controller issue, you can't select the Toggle Headers from SMLHelper in the mod options. 
https://github.com/SubnauticaModding/QModManager/issues/275

### LINKED ISSUE #289: Cannot interact with Mods menu using controller
For the stock Options menu you can navigate using a controller with the Dpad and A/B for select and back. Trying to enter the Mods menu with the controller highlights the Mods button but otherwise has no effect. You do need to hit back to get to any of the Stock options menus.

This is for version 2.15 on Subnautica Living Large update.

### PR DESCRIPTION
**Pull request by celvro**
1. GameInput is hardcoded to keyboard, changed to use primary device. This updates when the menu is opened. Maybe there's a better spot to attach the device changing so it works while the menu is open
2. Fixed when controller gets stuck on the HeadingToggle since it only has a click handler. Thanks @JKohlman for fixing the selected background and button toggle!
3. Added controller icons for the KeyBind input! this uses uGUI.buttonCharacters internally so theoretically it works with anything in that array

fixes #263, #289

### CODE REVIEW

**Review by 32Kallies — APPROVED** [review]
What I have seen is great and what I can test works well, although I don't have a controller myself to try. Regarding the code, it seems like a harmless change with very little room for errors.

**Comment by JKohlman** [comment]
Seems to work, does leave a couple issues/feature requests open - mainly actually showing selection on tabs and the Clear implementation

**Review by JKohlman — COMMENTED** [review]
Seems to work, does leave a couple issues/feature requests open - mainly actually showing selection on tabs and the Clear implementation.

@celvro are those things you'd want to look into for it or just at a later time?

**Comment by JKohlman** [comment]
Also not a huge issue but to note: scrolling down it seems like we do invisibly select the headers but scrolling up it seems like we just immediately skip over the header

**Review by JKohlman — CHANGES_REQUESTED** [review]
@celvro Please take a look at https://github.com/celvro/Nautilus/pull/1 for potentially more improvements and approve, modify or reject that before we can merge this.

In that PR there is still a bug where the cursor skips the option above each heading when scrolling upwards

**Comment by celvro** [comment]
Ok looks good! I also fixed ps4 icons, my controller was sending the wrong inputs but the icons looked correct for the buttons it was sending 🤷 

Here's a list of known issues, I'm fine merging as is and fixing incrementally:

1. Options don't update immediately when primary device changes, you have to close and open the menu first.
2. If you close the final options header, it lets you keep scrolling down and starts scrolling through tabs. You can't activate them until you hit back.
3. The clear button doesn't work.
4. When scrolling up from a header it skips one option.
5. If SMLHelper is installed, the options panel doesn't get patched. This is unrelated to the controller fixes and seems to be intentional, Nautilus checks it in OptionsPanelPatcher before patching.

**Comment by JKohlman** [comment]
I'm helping a family member move today but can you just confirm whether 2 and 4 are completely Nautilus bugs or whether they happen in vanilla game/options menus too?

**Comment by celvro** [comment]
Neither of them happen on vanilla but I don't think it has collapsible headers

On 4 I tested with a second mod installed and it _didn't_ skip over the last setting on that one. It still happened on the Nautilus option. Weird but imo it's not a big deal

**Comment by JKohlman** [comment]
Approved with the caveat that we note down the issues and take another crack at figuring them out but they're pretty weird/abstract

**Review by JKohlman — APPROVED** [review]

**Pull request merged**
