### PR TITLE
AddVFXFabricating

### PR DESCRIPTION
**Pull request by LeeTwentyThree**
### Changes made in this pull request

  - `AddVFXFabricating` method in `PrefabUtils`

### CODE REVIEW

**Review by EldritchCarMaker — COMMENTED** [review]
Position offset and path to model should probably be optional arguments as well

**Comment by LeeTwentyThree** [comment]
1. Since this is intended to be a one-line call, and models typically do not exist on the prefab root, path to child will be used in most cases.
2. Position offset could be optional, sure.

**Comment by EldritchCarMaker** [comment]
> * Since this is intended to be a one-line call, and models typically do not exist on the prefab root, path to child will be used in most cases.

Making it an optional argument won’t change it to/from a one line call, and there’s a not insignificant number of prefabs which do have models on the root. Largely this is only the case for tools, or smaller items like them, but they’re still there

**Comment by LeeTwentyThree** [comment]
Made some changes, but still would prefer to encourage people to consider that the model might need to be changed.

**Review by EldritchCarMaker — APPROVED** [review]

**Pull request merged**
